/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsConsoleConsoleCalculatorRouteImport } from './routes/projects/console/ConsoleCalculator'
import { Route as ProjectsConsoleConsoleHangmanRouteImport } from './routes/projects/console/ConsoleHangman'
import { Route as ProjectsConsoleConsoleSnakeRouteImport } from './routes/projects/console/ConsoleSnake'
import { Route as ProjectsGamesApagosRouteImport } from './routes/projects/games/Apagos'
import { Route as ProjectsGamesBlackjackCoopRouteImport } from './routes/projects/games/BlackjackCoop'
import { Route as ProjectsGamesNba2kRouteImport } from './routes/projects/games/Nba2k'
import { Route as ProjectsGamesNotASandboxRouteImport } from './routes/projects/games/NotASandbox'
import { Route as ProjectsGamesProgrammer101RouteImport } from './routes/projects/games/Programmer101'
import { Route as ProjectsGamesTheBoringRPGRouteImport } from './routes/projects/games/TheBoringRPG'
import { Route as ProjectsGamesTheGameRouteImport } from './routes/projects/games/TheGame'
import { Route as ProjectsHardwareServyRouteImport } from './routes/projects/hardware/Servy'
import { Route as ProjectsSoftwaresAuditoRouteImport } from './routes/projects/softwares/Audito'
import { Route as ProjectsSoftwaresFreeCarveRouteImport } from './routes/projects/softwares/FreeCarve'
import { Route as ProjectsSoftwaresNotDiscordRouteImport } from './routes/projects/softwares/NotDiscord'
import { Route as ProjectsSoftwaresTestingDirectX11RouteImport } from './routes/projects/softwares/TestingDirectX11'
import { Route as ProjectsWebsitesLouisMenagerieRouteImport } from './routes/projects/websites/LouisMenagerie'
import { Route as ProjectsWebsitesXPPortfolioRouteImport } from './routes/projects/websites/XPPortfolio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsConsoleConsoleCalculatorRoute =
  ProjectsConsoleConsoleCalculatorRouteImport.update({
    id: '/projects/console/ConsoleCalculator',
    path: '/projects/console/ConsoleCalculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsConsoleConsoleHangmanRoute =
  ProjectsConsoleConsoleHangmanRouteImport.update({
    id: '/projects/console/ConsoleHangman',
    path: '/projects/console/ConsoleHangman',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsConsoleConsoleSnakeRoute =
  ProjectsConsoleConsoleSnakeRouteImport.update({
    id: '/projects/console/ConsoleSnake',
    path: '/projects/console/ConsoleSnake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsGamesApagosRoute = ProjectsGamesApagosRouteImport.update({
  id: '/projects/games/Apagos',
  path: '/projects/games/Apagos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGamesBlackjackCoopRoute =
  ProjectsGamesBlackjackCoopRouteImport.update({
    id: '/projects/games/BlackjackCoop',
    path: '/projects/games/BlackjackCoop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsGamesNba2kRoute = ProjectsGamesNba2kRouteImport.update({
  id: '/projects/games/Nba2k',
  path: '/projects/games/Nba2k',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGamesNotASandboxRoute =
  ProjectsGamesNotASandboxRouteImport.update({
    id: '/projects/games/NotASandbox',
    path: '/projects/games/NotASandbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsGamesProgrammer101Route =
  ProjectsGamesProgrammer101RouteImport.update({
    id: '/projects/games/Programmer101',
    path: '/projects/games/Programmer101',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsGamesTheBoringRPGRoute =
  ProjectsGamesTheBoringRPGRouteImport.update({
    id: '/projects/games/TheBoringRPG',
    path: '/projects/games/TheBoringRPG',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsGamesTheGameRoute = ProjectsGamesTheGameRouteImport.update({
  id: '/projects/games/TheGame',
  path: '/projects/games/TheGame',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHardwareServyRoute = ProjectsHardwareServyRouteImport.update({
  id: '/projects/hardware/Servy',
  path: '/projects/hardware/Servy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSoftwaresAuditoRoute = ProjectsSoftwaresAuditoRouteImport.update({
  id: '/projects/softwares/Audito',
  path: '/projects/softwares/Audito',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSoftwaresFreeCarveRoute =
  ProjectsSoftwaresFreeCarveRouteImport.update({
    id: '/projects/softwares/FreeCarve',
    path: '/projects/softwares/FreeCarve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSoftwaresNotDiscordRoute =
  ProjectsSoftwaresNotDiscordRouteImport.update({
    id: '/projects/softwares/NotDiscord',
    path: '/projects/softwares/NotDiscord',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSoftwaresTestingDirectX11Route =
  ProjectsSoftwaresTestingDirectX11RouteImport.update({
    id: '/projects/softwares/TestingDirectX11',
    path: '/projects/softwares/TestingDirectX11',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsWebsitesLouisMenagerieRoute =
  ProjectsWebsitesLouisMenagerieRouteImport.update({
    id: '/projects/websites/LouisMenagerie',
    path: '/projects/websites/LouisMenagerie',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsWebsitesXPPortfolioRoute =
  ProjectsWebsitesXPPortfolioRouteImport.update({
    id: '/projects/websites/XPPortfolio',
    path: '/projects/websites/XPPortfolio',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/console/ConsoleCalculator': typeof ProjectsConsoleConsoleCalculatorRoute
  '/projects/console/ConsoleHangman': typeof ProjectsConsoleConsoleHangmanRoute
  '/projects/console/ConsoleSnake': typeof ProjectsConsoleConsoleSnakeRoute
  '/projects/games/Apagos': typeof ProjectsGamesApagosRoute
  '/projects/games/BlackjackCoop': typeof ProjectsGamesBlackjackCoopRoute
  '/projects/games/Nba2k': typeof ProjectsGamesNba2kRoute
  '/projects/games/NotASandbox': typeof ProjectsGamesNotASandboxRoute
  '/projects/games/Programmer101': typeof ProjectsGamesProgrammer101Route
  '/projects/games/TheBoringRPG': typeof ProjectsGamesTheBoringRPGRoute
  '/projects/games/TheGame': typeof ProjectsGamesTheGameRoute
  '/projects/hardware/Servy': typeof ProjectsHardwareServyRoute
  '/projects/softwares/Audito': typeof ProjectsSoftwaresAuditoRoute
  '/projects/softwares/FreeCarve': typeof ProjectsSoftwaresFreeCarveRoute
  '/projects/softwares/NotDiscord': typeof ProjectsSoftwaresNotDiscordRoute
  '/projects/softwares/TestingDirectX11': typeof ProjectsSoftwaresTestingDirectX11Route
  '/projects/websites/LouisMenagerie': typeof ProjectsWebsitesLouisMenagerieRoute
  '/projects/websites/XPPortfolio': typeof ProjectsWebsitesXPPortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/console/ConsoleCalculator': typeof ProjectsConsoleConsoleCalculatorRoute
  '/projects/console/ConsoleHangman': typeof ProjectsConsoleConsoleHangmanRoute
  '/projects/console/ConsoleSnake': typeof ProjectsConsoleConsoleSnakeRoute
  '/projects/games/Apagos': typeof ProjectsGamesApagosRoute
  '/projects/games/BlackjackCoop': typeof ProjectsGamesBlackjackCoopRoute
  '/projects/games/Nba2k': typeof ProjectsGamesNba2kRoute
  '/projects/games/NotASandbox': typeof ProjectsGamesNotASandboxRoute
  '/projects/games/Programmer101': typeof ProjectsGamesProgrammer101Route
  '/projects/games/TheBoringRPG': typeof ProjectsGamesTheBoringRPGRoute
  '/projects/games/TheGame': typeof ProjectsGamesTheGameRoute
  '/projects/hardware/Servy': typeof ProjectsHardwareServyRoute
  '/projects/softwares/Audito': typeof ProjectsSoftwaresAuditoRoute
  '/projects/softwares/FreeCarve': typeof ProjectsSoftwaresFreeCarveRoute
  '/projects/softwares/NotDiscord': typeof ProjectsSoftwaresNotDiscordRoute
  '/projects/softwares/TestingDirectX11': typeof ProjectsSoftwaresTestingDirectX11Route
  '/projects/websites/LouisMenagerie': typeof ProjectsWebsitesLouisMenagerieRoute
  '/projects/websites/XPPortfolio': typeof ProjectsWebsitesXPPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/console/ConsoleCalculator': typeof ProjectsConsoleConsoleCalculatorRoute
  '/projects/console/ConsoleHangman': typeof ProjectsConsoleConsoleHangmanRoute
  '/projects/console/ConsoleSnake': typeof ProjectsConsoleConsoleSnakeRoute
  '/projects/games/Apagos': typeof ProjectsGamesApagosRoute
  '/projects/games/BlackjackCoop': typeof ProjectsGamesBlackjackCoopRoute
  '/projects/games/Nba2k': typeof ProjectsGamesNba2kRoute
  '/projects/games/NotASandbox': typeof ProjectsGamesNotASandboxRoute
  '/projects/games/Programmer101': typeof ProjectsGamesProgrammer101Route
  '/projects/games/TheBoringRPG': typeof ProjectsGamesTheBoringRPGRoute
  '/projects/games/TheGame': typeof ProjectsGamesTheGameRoute
  '/projects/hardware/Servy': typeof ProjectsHardwareServyRoute
  '/projects/softwares/Audito': typeof ProjectsSoftwaresAuditoRoute
  '/projects/softwares/FreeCarve': typeof ProjectsSoftwaresFreeCarveRoute
  '/projects/softwares/NotDiscord': typeof ProjectsSoftwaresNotDiscordRoute
  '/projects/softwares/TestingDirectX11': typeof ProjectsSoftwaresTestingDirectX11Route
  '/projects/websites/LouisMenagerie': typeof ProjectsWebsitesLouisMenagerieRoute
  '/projects/websites/XPPortfolio': typeof ProjectsWebsitesXPPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/projects/'
    | '/projects/console/ConsoleCalculator'
    | '/projects/console/ConsoleHangman'
    | '/projects/console/ConsoleSnake'
    | '/projects/games/Apagos'
    | '/projects/games/BlackjackCoop'
    | '/projects/games/Nba2k'
    | '/projects/games/NotASandbox'
    | '/projects/games/Programmer101'
    | '/projects/games/TheBoringRPG'
    | '/projects/games/TheGame'
    | '/projects/hardware/Servy'
    | '/projects/softwares/Audito'
    | '/projects/softwares/FreeCarve'
    | '/projects/softwares/NotDiscord'
    | '/projects/softwares/TestingDirectX11'
    | '/projects/websites/LouisMenagerie'
    | '/projects/websites/XPPortfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects'
    | '/projects/console/ConsoleCalculator'
    | '/projects/console/ConsoleHangman'
    | '/projects/console/ConsoleSnake'
    | '/projects/games/Apagos'
    | '/projects/games/BlackjackCoop'
    | '/projects/games/Nba2k'
    | '/projects/games/NotASandbox'
    | '/projects/games/Programmer101'
    | '/projects/games/TheBoringRPG'
    | '/projects/games/TheGame'
    | '/projects/hardware/Servy'
    | '/projects/softwares/Audito'
    | '/projects/softwares/FreeCarve'
    | '/projects/softwares/NotDiscord'
    | '/projects/softwares/TestingDirectX11'
    | '/projects/websites/LouisMenagerie'
    | '/projects/websites/XPPortfolio'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/projects/'
    | '/projects/console/ConsoleCalculator'
    | '/projects/console/ConsoleHangman'
    | '/projects/console/ConsoleSnake'
    | '/projects/games/Apagos'
    | '/projects/games/BlackjackCoop'
    | '/projects/games/Nba2k'
    | '/projects/games/NotASandbox'
    | '/projects/games/Programmer101'
    | '/projects/games/TheBoringRPG'
    | '/projects/games/TheGame'
    | '/projects/hardware/Servy'
    | '/projects/softwares/Audito'
    | '/projects/softwares/FreeCarve'
    | '/projects/softwares/NotDiscord'
    | '/projects/softwares/TestingDirectX11'
    | '/projects/websites/LouisMenagerie'
    | '/projects/websites/XPPortfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsConsoleConsoleCalculatorRoute: typeof ProjectsConsoleConsoleCalculatorRoute
  ProjectsConsoleConsoleHangmanRoute: typeof ProjectsConsoleConsoleHangmanRoute
  ProjectsConsoleConsoleSnakeRoute: typeof ProjectsConsoleConsoleSnakeRoute
  ProjectsGamesApagosRoute: typeof ProjectsGamesApagosRoute
  ProjectsGamesBlackjackCoopRoute: typeof ProjectsGamesBlackjackCoopRoute
  ProjectsGamesNba2kRoute: typeof ProjectsGamesNba2kRoute
  ProjectsGamesNotASandboxRoute: typeof ProjectsGamesNotASandboxRoute
  ProjectsGamesProgrammer101Route: typeof ProjectsGamesProgrammer101Route
  ProjectsGamesTheBoringRPGRoute: typeof ProjectsGamesTheBoringRPGRoute
  ProjectsGamesTheGameRoute: typeof ProjectsGamesTheGameRoute
  ProjectsHardwareServyRoute: typeof ProjectsHardwareServyRoute
  ProjectsSoftwaresAuditoRoute: typeof ProjectsSoftwaresAuditoRoute
  ProjectsSoftwaresFreeCarveRoute: typeof ProjectsSoftwaresFreeCarveRoute
  ProjectsSoftwaresNotDiscordRoute: typeof ProjectsSoftwaresNotDiscordRoute
  ProjectsSoftwaresTestingDirectX11Route: typeof ProjectsSoftwaresTestingDirectX11Route
  ProjectsWebsitesLouisMenagerieRoute: typeof ProjectsWebsitesLouisMenagerieRoute
  ProjectsWebsitesXPPortfolioRoute: typeof ProjectsWebsitesXPPortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/console/ConsoleCalculator': {
      id: '/projects/console/ConsoleCalculator'
      path: '/projects/console/ConsoleCalculator'
      fullPath: '/projects/console/ConsoleCalculator'
      preLoaderRoute: typeof ProjectsConsoleConsoleCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/console/ConsoleHangman': {
      id: '/projects/console/ConsoleHangman'
      path: '/projects/console/ConsoleHangman'
      fullPath: '/projects/console/ConsoleHangman'
      preLoaderRoute: typeof ProjectsConsoleConsoleHangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/console/ConsoleSnake': {
      id: '/projects/console/ConsoleSnake'
      path: '/projects/console/ConsoleSnake'
      fullPath: '/projects/console/ConsoleSnake'
      preLoaderRoute: typeof ProjectsConsoleConsoleSnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/Apagos': {
      id: '/projects/games/Apagos'
      path: '/projects/games/Apagos'
      fullPath: '/projects/games/Apagos'
      preLoaderRoute: typeof ProjectsGamesApagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/BlackjackCoop': {
      id: '/projects/games/BlackjackCoop'
      path: '/projects/games/BlackjackCoop'
      fullPath: '/projects/games/BlackjackCoop'
      preLoaderRoute: typeof ProjectsGamesBlackjackCoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/Nba2k': {
      id: '/projects/games/Nba2k'
      path: '/projects/games/Nba2k'
      fullPath: '/projects/games/Nba2k'
      preLoaderRoute: typeof ProjectsGamesNba2kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/NotASandbox': {
      id: '/projects/games/NotASandbox'
      path: '/projects/games/NotASandbox'
      fullPath: '/projects/games/NotASandbox'
      preLoaderRoute: typeof ProjectsGamesNotASandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/Programmer101': {
      id: '/projects/games/Programmer101'
      path: '/projects/games/Programmer101'
      fullPath: '/projects/games/Programmer101'
      preLoaderRoute: typeof ProjectsGamesProgrammer101RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/TheBoringRPG': {
      id: '/projects/games/TheBoringRPG'
      path: '/projects/games/TheBoringRPG'
      fullPath: '/projects/games/TheBoringRPG'
      preLoaderRoute: typeof ProjectsGamesTheBoringRPGRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/games/TheGame': {
      id: '/projects/games/TheGame'
      path: '/projects/games/TheGame'
      fullPath: '/projects/games/TheGame'
      preLoaderRoute: typeof ProjectsGamesTheGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/hardware/Servy': {
      id: '/projects/hardware/Servy'
      path: '/projects/hardware/Servy'
      fullPath: '/projects/hardware/Servy'
      preLoaderRoute: typeof ProjectsHardwareServyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/softwares/Audito': {
      id: '/projects/softwares/Audito'
      path: '/projects/softwares/Audito'
      fullPath: '/projects/softwares/Audito'
      preLoaderRoute: typeof ProjectsSoftwaresAuditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/softwares/FreeCarve': {
      id: '/projects/softwares/FreeCarve'
      path: '/projects/softwares/FreeCarve'
      fullPath: '/projects/softwares/FreeCarve'
      preLoaderRoute: typeof ProjectsSoftwaresFreeCarveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/softwares/NotDiscord': {
      id: '/projects/softwares/NotDiscord'
      path: '/projects/softwares/NotDiscord'
      fullPath: '/projects/softwares/NotDiscord'
      preLoaderRoute: typeof ProjectsSoftwaresNotDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/softwares/TestingDirectX11': {
      id: '/projects/softwares/TestingDirectX11'
      path: '/projects/softwares/TestingDirectX11'
      fullPath: '/projects/softwares/TestingDirectX11'
      preLoaderRoute: typeof ProjectsSoftwaresTestingDirectX11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/websites/LouisMenagerie': {
      id: '/projects/websites/LouisMenagerie'
      path: '/projects/websites/LouisMenagerie'
      fullPath: '/projects/websites/LouisMenagerie'
      preLoaderRoute: typeof ProjectsWebsitesLouisMenagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/websites/XPPortfolio': {
      id: '/projects/websites/XPPortfolio'
      path: '/projects/websites/XPPortfolio'
      fullPath: '/projects/websites/XPPortfolio'
      preLoaderRoute: typeof ProjectsWebsitesXPPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsConsoleConsoleCalculatorRoute: ProjectsConsoleConsoleCalculatorRoute,
  ProjectsConsoleConsoleHangmanRoute: ProjectsConsoleConsoleHangmanRoute,
  ProjectsConsoleConsoleSnakeRoute: ProjectsConsoleConsoleSnakeRoute,
  ProjectsGamesApagosRoute: ProjectsGamesApagosRoute,
  ProjectsGamesBlackjackCoopRoute: ProjectsGamesBlackjackCoopRoute,
  ProjectsGamesNba2kRoute: ProjectsGamesNba2kRoute,
  ProjectsGamesNotASandboxRoute: ProjectsGamesNotASandboxRoute,
  ProjectsGamesProgrammer101Route: ProjectsGamesProgrammer101Route,
  ProjectsGamesTheBoringRPGRoute: ProjectsGamesTheBoringRPGRoute,
  ProjectsGamesTheGameRoute: ProjectsGamesTheGameRoute,
  ProjectsHardwareServyRoute: ProjectsHardwareServyRoute,
  ProjectsSoftwaresAuditoRoute: ProjectsSoftwaresAuditoRoute,
  ProjectsSoftwaresFreeCarveRoute: ProjectsSoftwaresFreeCarveRoute,
  ProjectsSoftwaresNotDiscordRoute: ProjectsSoftwaresNotDiscordRoute,
  ProjectsSoftwaresTestingDirectX11Route:
    ProjectsSoftwaresTestingDirectX11Route,
  ProjectsWebsitesLouisMenagerieRoute: ProjectsWebsitesLouisMenagerieRoute,
  ProjectsWebsitesXPPortfolioRoute: ProjectsWebsitesXPPortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
